name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Har 12 ghante me chalega
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Commit snake
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
